### ISSUE TITLE
Delete Object

### ISSUE THREAD

**Issue by appcelerate** [MarcoSero/Nimble#27] opened 2015-05-26 14:27 UTC
How can i delete an Object from iCloud and NimbleStore?
With MagicalRecord(used before) there was an option mr_DeleteEntitiy.

Regards

**Comment by MarcoSero** [comment] 2015-05-26 14:38
Duplicate of https://github.com/MarcoSero/Nimble/issues/4

**Closed by MarcoSero** 2015-05-26 14:38 UTC
Labels: duplicate
